### PR TITLE
Update index.m3u8

### PR DESCRIPTION
**Pull request by gio299**

### CODE REVIEW

**Comment by gio299** [comment]
hi! all streams from twitch dont work!

Στις Δευ 11 Δεκ 2023 στις 1:11 π.μ., ο/η Azgar ***@***.***>
έγραψε:

**Comment by azgaresncf** [comment]
Hi! Thank you for reporting this bug!
I think we are just unfortunately unlucky, because if you copy and paste the link into VLC, it doesn't work. But if we either download the m3u8 or copy and paste an OLDER file, it does work ???

Can you give the channels that you want please?

**Comment by azgaresncf** [comment]
By the way, if you want to report any bugs or anything like that, please make an issue here ;)
https://github.com/azgaresncf/strm2hls/issues/new

**Comment by gio299** [comment]
on vlc or android tv all streams from  twitch dont work!

Στις Παρ 29 Δεκ 2023 στις 8:52 μ.μ., ο/η Azgar ***@***.***>
έγραψε:

**Comment by gio299** [comment]
all channels that i want its inside on  index.m3u8

Στις Παρ 29 Δεκ 2023 στις 8:57 μ.μ., ο/η Maria Papathanasiou <
***@***.***> έγραψε:

**Comment by gio299** [comment]
#EXTINF:-1,thessalia tv
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/thessaliatv.m3u8
#EXTINF:-1,Dion TV
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/DionTVKentrikisMakedonias.m3u8
#EXTINF:-1,Rodopi TV
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/TVRodopi.m3u8
#EXTINF:-1,Tileorasi Kosmos ΡΟΔΟΣ
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvkosmosgr.m3u8
#EXTINF:-1,VERGINA TV
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/verginachannel.m3u8
#EXTINF:-1,Lepanto TV ΠΑΤΡΑ
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/LePanto.m3u8
#EXTINF:-1,Flash TV Kozani
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/FlashTV.m3u8
#EXTINF:-1,STAR Βορείου Ελλάδος
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvstarfm.m3u8
#EXTINF:-1,STAR Κεντρικής Ελλάδας
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/StarL.m3u8
#EXTINF:-1,TOP CHANNEL ΚΟΖΑΝΗ
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/Top_Channel_Greece.m3u8
#EXTINF:-1,Pronews TV ΠΑΤΡΑ
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/ProNews.m3u8
#EXTINF:-1,TV ΙΩΝΙΑ ΘΕΣΣΑΛΟΝΙΚΗΣ
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvioniathessalonikis.m3u8
#EXTINF:-1,CENTER TV ΚΑΒΑΛΑ
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/centertv.m3u8








Στις Παρ 29 Δεκ 2023 στις 8:58 μ.μ., ο/η Maria Papathanasiou <
***@***.***> έγραψε:

**Pull request merged**
