### PR TITLE
adding StarL

### PR DESCRIPTION
**Pull request by gio299**

### CODE REVIEW

**Comment by gio299** [comment]
star lamias
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/StarL.m3u8
no more exist .please delete this stream.
i was put new stream with new name Star Kentrikis Eladas

Στις Παρ 19 Ιαν 2024 στις 9:29 π.μ., ο/η Azgar ***@***.***>
έγραψε:

**Comment by gio299** [comment]
all twitch streams not (NOT 24/7)
e.g
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/FlashTV.m3u8
not working but
 twitch stream its working
https://www.twitch.tv/flashtvgr


Στις Παρ 19 Ιαν 2024 στις 10:43 π.μ., ο/η Maria Papathanasiou <
***@***.***> έγραψε:

**Comment by gio299** [comment]
e.g
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/DionTVKentrikisMakedonias.m3u8
 not working (NOT 24/7)
now its down
 twitch stream its working 100%
https://www.twitch.tv/diontvkentrikismakedonias


what is going on? can you fix it please?

Στις Παρ 19 Ιαν 2024 στις 10:55 π.μ., ο/η Maria Papathanasiou <
***@***.***> έγραψε:

**Comment by gio299** [comment]
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/verginatv_cyprus.m3u8
not
(24-7) NOW ITS DOWN BUT
TWITCH STREAM WORK 100%

https://www.twitch.tv/verginacy


Στις Παρ 19 Ιαν 2024 στις 11:01 π.μ., ο/η Maria Papathanasiou <
***@***.***> έγραψε:

**Comment by azgaresncf** [comment]
wow, thank you, it is a mess ☠️

**Comment by gio299** [comment]
Can you check the script please? dailymotion streams and twitch streams
working only a few hours,and then, we  must wait some hours to grab a new
stream!

Can you fix it please?

We need (24/7) not (6/24)😀😀😀😀😀

Στις Παρ 19 Ιαν 2024 στις 5:28 μ.μ., ο/η Azgar ***@***.***>
έγραψε:

**Comment by gio299** [comment]
Can you grab epg  please from   https://watch.antennaplus.gr/#/tv-guide

Its about 9 channels!

Thanks a lot my fried !!!!!

Ps : IT IS VERY IMPORTANT FOR ME!

**Pull request merged**
